<a href="https://colab.research.google.com/github/Phanttan/DeepLearning-Miscellanious/blob/main/Chasing_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [2]:
import numpy as np
import tensorflow as tf

# Definition
we know a vector is a one-dimension array.
Continuously, a matrix is a two-dimension array.
So, what happen if have a object with more-than-two-dimension array, it is really exist. 
==> Tensor : we can define infinitive-dimension array.

In [6]:
rank_0_tensor = tf.constant(4)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [11]:
rank_1_tensor = tf.constant([[1,2,3,4]]) # As a vector
rank_1_tensor

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [26]:
rank_2_tensor = tf.constant([[1,2,3],
                             [5,6,7]]) # As a matrix
rank_2_tensor

TypeError: ignored

In [16]:
rank_3_tensor = tf.constant([[[1,2],
                              [3,4],],
                             
                              [[5,6],
                              [7,8],],
                             ])
rank_3_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

# Convert Tensor

In [18]:
rank_3_numpy1 = rank_3_tensor.numpy()
rank_3_numpy1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [19]:
rank_3_numpy2 = np.array(rank_3_tensor)
rank_3_numpy2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

# Tensor Operation

In [41]:
a = tf.constant([[1,2],
                 [3,4]], dtype='float32')
b = tf.ones([2,2])


In [42]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [38]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

## Element-wide multiplication

In [43]:

a*b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [44]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## Matrix Multiplication

In [45]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [7., 7.]], dtype=float32)>

In [46]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [7., 7.]], dtype=float32)>

## Adding

In [47]:
a + b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [48]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

## Largest Value

In [49]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

## Index of the largest value

In [50]:
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

## Sigmoid

In [51]:
tf.sigmoid(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7310586 , 0.8807971 ],
       [0.95257413, 0.98201376]], dtype=float32)>