<a href="https://colab.research.google.com/github/Phanttan/DeepLearning-Miscellanious/blob/main/MaxPooling2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf

# Create samplings

## (3x3)

In [24]:
x = tf.constant([[1,2,3],
                 [4,5,2],
                 [7,8,9]])
x = tf.reshape(x,[1,3,3,1])
x

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [2]],

        [[7],
         [8],
         [9]]]], dtype=int32)>

## (4x4)

In [25]:
y = tf.constant([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
y = tf.reshape(y,[1,4,4,1])
y

<tf.Tensor: shape=(1, 4, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]],

        [[13],
         [14],
         [15],
         [16]]]], dtype=int32)>

# Define Layers with changing Strides, padding='valid'
output_shape = (input_shape - pool_size + 1) / strides)

In [26]:
layer1 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(1,1), padding='valid')
layer2 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding='valid')
layer3 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(1,2), padding='valid')
layer4 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,1), padding='valid')

## Result in (3x3) 

In [27]:
layer1(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[5],
         [5]],

        [[8],
         [9]]]], dtype=int32)>

In [ ]:
layer2(x)

## Result in (4x4)

In [28]:
layer1(y)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[ 6],
         [ 7],
         [ 8]],

        [[10],
         [11],
         [12]],

        [[14],
         [15],
         [16]]]], dtype=int32)>

In [29]:
layer2(y)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[ 6],
         [ 8]],

        [[14],
         [16]]]], dtype=int32)>

In [30]:
layer3(y)

<tf.Tensor: shape=(1, 3, 2, 1), dtype=int32, numpy=
array([[[[ 6],
         [ 8]],

        [[10],
         [12]],

        [[14],
         [16]]]], dtype=int32)>

In [31]:
layer4(y)

<tf.Tensor: shape=(1, 2, 3, 1), dtype=int32, numpy=
array([[[[ 6],
         [ 7],
         [ 8]],

        [[14],
         [15],
         [16]]]], dtype=int32)>

# Define Layers with changing Strides, padding='same'
output_shape = input_shape / strides



In [32]:
layer5 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(1,1), padding='same')
layer6 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding='same')
layer7 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,1), padding='same')
layer8 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(1,2), padding='same')

## Result in (3x3)

In [33]:
layer5(x)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[5],
         [5],
         [3]],

        [[8],
         [9],
         [9]],

        [[8],
         [9],
         [9]]]], dtype=int32)>

In [34]:
layer6(x)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[5],
         [3]],

        [[8],
         [9]]]], dtype=int32)>